[package]
name = "incognichat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "./src/server.rs"

[[bin]]
name = "client"
path = "./src/client.rs"

[dependencies]
chrono = "0.4.39"
crossterm = "0.28.1"
smol = "2.0.2"
