[package]
name = "incognichat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "backend"
path = "./src/backend.rs"

[[bin]]
name = "frontend"
path = "./src/frontend.rs"

[dependencies]
chrono = "0.4.39"
crossterm = "0.28.1"
